[workspace]
members = ["kernel", "bootstrap", "shell", "libuser", "clock", "sm", "vi", "ahci", "libutils", "libkern", "swipc-gen", "swipc-parser", "virtio"]

[profile.release]
debug = true

[profile.test]
debug = true
