[config]
skip_core_tasks = true

[env]
RUST_TARGET_PATH = "${PWD}"
GDB_PORT = { script = ["echo ${GDB_PORT:-9090}"] }
VNC_PORT = { script = ["echo ${VNC_PORT:-:0}"] }
CLIPPY_RULES = """
-A clippy::redundant_field_names \
-A clippy::unreadable_literal \
-A clippy::identity_op \
-A clippy::zero_prefixed_literal \
-A clippy::redundant_closure \
-W clippy::cast_possible_wrap \
-W clippy::cast_sign_loss \
-W clippy::default_trait_access \
-W clippy::explicit_into_iter_loop \
-W clippy::explicit_iter_loop \
-W clippy::missing_docs_in_private_items \
-W clippy::mut_mut \
-W clippy::replace_consts \
-W clippy::used_underscore_binding \
-W clippy::wildcard_dependencies \
-W clippy::wrong_pub_self_convention"""


[tasks.bootstrap-linker]
workspace = false
script_runner = "@shell"
script = ["cp linker-scripts/bootstrap.ld link.T"]

[tasks.kernel-linker]
workspace = false
script_runner = "@shell"
script = ["cp linker-scripts/kernel.ld    link.T"]

[tasks.install-rust-src]
install_crate = { rustup_component_name = "rust-src" }

[tasks.install-mkisofs-rs]
install_crate = { crate_name = "mkisofs-rs", binary = "mkisofs-rs", test_arg = "--help" }

[tasks.bootstrap]
workspace = false
description = "Compiles the i386 bootstrap for debug"
dependencies = ["bootstrap-linker", "install-rust-src"]
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none", "--package=sunrise-bootstrap" ]

[tasks.bootstrap-release]
workspace = false
description = "Compiles the i386 bootstrap for release"
dependencies = ["bootstrap-linker", "install-rust-src"]
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none", "--package=sunrise-bootstrap", "--release" ]

[tasks.kernel]
workspace = false
description = "Compiles the kernel for debug"
dependencies = ["kernel-linker", "install-rust-src"]
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none", "--package=sunrise-kernel", "-Z", "package-features", "--features=panic-on-exception"]

[tasks.kernel-release]
workspace = false
description = "Compiles the kernel for release"
dependencies = ["kernel-linker", "install-rust-src"]
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none", "--package=sunrise-kernel", "--release" ]

[tasks.vi]
workspace = false
description = "Compiles sunrise-vi"
dependencies = ["install-rust-src"]
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none-user", "--package=sunrise-vi"]

[tasks.vi-release]
workspace = false
description = "Compiles sunrise-vi"
dependencies = ["install-rust-src"]
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none-user", "--package=sunrise-vi", "--release"]

[tasks.sm]
workspace = false
description = "Compiles sunrise-sm"
dependencies = ["install-rust-src"]
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none-user", "--package=sunrise-sm"]

[tasks.sm-release]
workspace = false
description = "Compiles sunrise-sm"
dependencies = ["install-rust-src"]
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none-user", "--package=sunrise-sm", "--release"]

[tasks.shell]
workspace = false
description = "Compiles sunrise-shell"
dependencies = ["install-rust-src"]
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none-user", "--package=sunrise-shell"]

[tasks.shell-release]
workspace = false
description = "Compiles sunrise-shell"
dependencies = ["install-rust-src"]
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none-user", "--package=sunrise-shell", "--release"]

[tasks.clock]
workspace = false
description = "Compiles sunrise-clock"
dependencies = ["install-rust-src"]
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none-user", "--package=sunrise-clock"]

[tasks.clock-release]
workspace = false
description = "Compiles sunrise-clock"
dependencies = ["install-rust-src"]
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none-user", "--package=sunrise-clock", "--release"]

[tasks.ahci]
workspace = false
description = "Compiles sunrise-ahci"
dependencies = ["install-rust-src"]
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none-user", "--package=sunrise-ahci"]

[tasks.ahci-release]
workspace = false
description = "Compiles sunrise-ahci"
dependencies = ["install-rust-src"]
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none-user", "--package=sunrise-ahci", "--release"]

[tasks.virtio]
workspace = false
description = "Compiles sunrise-virtio"
dependencies = ["install-rust-src"]
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none-user", "--package=sunrise-virtio"]

[tasks.virtio-release]
workspace = false
description = "Compiles sunrise-virtio"
dependencies = ["install-rust-src"]
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none-user", "--package=sunrise-virtio", "--release"]


[tasks.userspace]
workspace = false
description = "Compiles userspace apps"
dependencies = ["shell", "clock", "sm", "vi", "ahci", "virtio"]

[tasks.userspace-release]
workspace = false
description = "Compiles userspace apps"
dependencies = ["shell-release", "clock-release", "sm-release", "vi-release", "ahci-release", "virtio-release"]

[tasks.iso]
workspace = false
description = "Creates a bootable ISO containing the kernel and grub."
dependencies = ["bootstrap", "kernel", "userspace", "install-mkisofs-rs"]
script_runner = "@shell"
script = [
'''
cp target/i386-unknown-none/debug/sunrise-bootstrap isofiles/boot/
cp target/i386-unknown-none/debug/sunrise-kernel    isofiles/boot/
cp target/i386-unknown-none-user/debug/sunrise-shell     isofiles/boot/
cp target/i386-unknown-none-user/debug/sunrise-clock     isofiles/boot/
cp target/i386-unknown-none-user/debug/sunrise-sm        isofiles/boot/
cp target/i386-unknown-none-user/debug/sunrise-vi        isofiles/boot/
cp target/i386-unknown-none-user/debug/sunrise-ahci      isofiles/boot/
cp target/i386-unknown-none-user/debug/sunrise-virtio    isofiles/boot/
mkisofs-rs external/grub/isofiles isofiles -o os.iso -b boot/grub/i386-pc/eltorito.img --no-emul-boot --boot-info-table --embedded-boot external/grub/embedded.img
'''
]

[tasks.iso-release]
workspace = false
description = "Creates a bootable ISO containing the kernel and grub."
dependencies = ["bootstrap-release", "kernel-release", "userspace-release", "install-mkisofs-rs"]
script_runner = "@shell"
script = [
'''
cp target/i386-unknown-none/release/sunrise-bootstrap isofiles/boot/
cp target/i386-unknown-none/release/sunrise-kernel    isofiles/boot/
cp target/i386-unknown-none-user/release/sunrise-shell     isofiles/boot/
cp target/i386-unknown-none-user/release/sunrise-clock     isofiles/boot/
cp target/i386-unknown-none-user/release/sunrise-sm        isofiles/boot/
cp target/i386-unknown-none-user/release/sunrise-vi        isofiles/boot/
cp target/i386-unknown-none-user/release/sunrise-ahci      isofiles/boot/
cp target/i386-unknown-none-user/release/sunrise-virtio    isofiles/boot/
mkisofs-rs external/grub/isofiles isofiles -o os.iso -b boot/grub/i386-pc/eltorito.img --no-emul-boot --boot-info-table --embedded-boot external/grub/embedded.img
'''
]

[tasks.disk]
workspace = false
description = "Creates an empty disk image."
command = "dd"
# 16384 = 8MiB / 512
# 512 is the block size, 8MiB is the target disk size.
args = [ "if=/dev/zero", "of=DISK.img", "count=16384", "bs=512" ]

[tasks.disk.windows]
command = "fsutil"
# Chosen by fair dice roll.
# 8388608 = 8MiB in bytes
args = [ "file", "createnew", "DISK.img", "8388608" ]

# because we can't have a dependency on a file ರ_ರ
[tasks.create-disk-if-not-exist]
workspace = false
description = "Invokes the task `disk` if DISK.img does not already exist."
condition_script = [ "[ ! -e DISK.img ]" ]
run_task = "disk"

[tasks.create-disk-if-not-exist.windows]
condition_script = [ "if exists DISK.img exit 1" ]

[tasks.qemu]
workspace = false
description = "Runs the bootable ISO in qemu."
dependencies = ["iso-release", "create-disk-if-not-exist"]
command = "qemu-system-i386"
args = [
    # Boot device
    "-cdrom", "os.iso",
    # Redirect serial to STDIO
    "-serial", "mon:stdio",
    # Redirect graphics to VNC
    "-vnc", "${VNC_PORT}",
    # Don't reboot on triple fault 
    "-no-reboot",
    # Enable hardware acceleration
    #"-enable-kvm",
    # Setup an AHCI device, with a disk on the first IDE port.
    "-drive", "id=diskA,file=DISK.img,format=raw,if=none", "-device", "ahci,id=ahci", "-device", "ide-drive,drive=diskA,bus=ahci.0",
    "-machine", "q35",
    # Setup a network device, using virtio-net.
    # TODO: iommu_platform=true
    "-device", "virtio-net,disable-legacy=on,netdev=u1", "-netdev", "user,id=u1",
    # Dump packets going on the vlan
    "-object", "filter-dump,id=f1,netdev=u1,file=dump.dat",
    # Trace virtio-related events
    "--trace", "virtio_set_status,file=trace", "--trace", "virtio_queue_notify,file=trace", "--trace", "virtio_notify,file=trace", "--trace", "virtio_input_queue_full,file=trace",
    "--trace", "virtio_net_announce_notify,file=trace", "--trace", "virtio_net_announce_timer,file=trace", "--trace", "virtio_net_handle_announce,file=trace",
    "--trace", "virtio_net_post_load_device,file=trace", "--trace", "virtio_notify_irqfd,file=trace",
]

[tasks.qemu-debug]
workspace = false
description = "Runs the bootable ISO in qemu with gdb support"
dependencies = ["iso", "create-disk-if-not-exist"]
command = "qemu-system-i386"
args = [
    # Boot device
    "-cdrom", "os.iso",
    # Redirect serial to STDIO
    "-serial", "mon:stdio",
    # Redirect graphics to VNC
    "-vnc", "${VNC_PORT}",
    # Enable hardware acceleration
    #"-enable-kvm",
    # Setup an AHCI device, with a disk on the first IDE port.
    "-drive", "id=diskA,file=DISK.img,format=raw,if=none", "-device", "ahci,id=ahci", "-device", "ide-drive,drive=diskA,bus=ahci.0",
    # Setup a network device, using virtio-net.
    # TODO: ,iommu_platform=true
    "-device", "virtio-net,disable-legacy=on,netdev=u1", "-netdev", "user,id=u1",
    # Dump packets going on the vlan
    "-object", "filter-dump,id=f1,netdev=u1,file=dump.dat",

    # Enable GDB
    "-gdb", "tcp::${GDB_PORT}", "-S",
    # Print state on CPU reset
    "-d", "cpu_reset",
    "-drive", "id=diskA,file=DISK.img,format=raw,if=none", "-device", "ahci,id=ahci", "-device", "ide-drive,drive=diskA,bus=ahci.0",
    "-machine", "q35",
    # Trace virtio-related events
    "--trace", "virtio_set_status,file=trace", "--trace", "virtio_queue_notify,file=trace", "--trace", "virtio_notify,file=trace", "--trace", "virtio_input_queue_full,file=trace",
    "--trace", "virtio_net_announce_notify,file=trace", "--trace", "virtio_net_announce_timer,file=trace", "--trace", "virtio_net_handle_announce,file=trace",
    "--trace", "virtio_net_post_load_device,file=trace", "--trace", "virtio_notify_irqfd,file=trace",
]

[tasks.doc]
workspace = false
description = "Generate the project's documentation"
env = { "RUSTFLAGS" = "--sysroot=${PWD}/target/sysroot",  "RUSTDOCFLAGS" = "--sysroot=${PWD}/target/sysroot"}
command = "cargo"
args = ["doc", "--no-deps" ]

[tasks.doc-full]
workspace = false
description = "Generate the project's documentation, including private items"
env = { "RUSTFLAGS" = "--sysroot=${PWD}/target/sysroot",  "RUSTDOCFLAGS" = "--sysroot=${PWD}/target/sysroot -Z unstable-options --enable-index-page"}
command = "cargo"
args = ["doc", "--no-deps", "--document-private-items"]

[tasks.deploy-doc]
workspace = false
install_crate = { crate_name = "cargo-travis", binary = "cargo", test_arg = ["doc-upload", "--help"] }
install_crate_args = ["--git", "https://github.com/roblabla/cargo-travis", "--rev", "doc-upload-target"]
description = "Upload this project's documentation on github pages. Should only run on CI."
command = "cargo"
args = ["doc-upload", "--clobber-index"]

[tasks.test]
workspace = false
description = "Run the tests in 32bit mode"
command = "cargo"
args = ["test", "--target=i686-unknown-linux-gnu"]

[tasks.refresh-crates]
workspace = false
description = "Make cargo-clippy work..."
command = "touch"
args = ["-c", "kernel/src/main.rs", "bootstrap/src/main.rs",
	"shell/src/main.rs", "libuser/src/lib.rs", "clock/src/main.rs",
	"sm/src/main.rs", "vi/src/main.rs", "ahci/src/main.rs",
	"libutils/src/lib.rs", "libkern/src/lib.rs", "swipc-gen/src/lib.rs",
	"swipc-parser/src/lib.rs", "virtio/src/main.rs",
]

[tasks.clippy-sunrise-target]
workspace = false
description = "Run clippy on sunrise components"
dependencies = ["install-rust-src", "refresh-crates"]
install_crate = { rustup_component_name = "clippy" }
command = "cargo"
args = ["xclippy", "--target=i386-unknown-none",
	"--all", "--exclude", "swipc-gen", "--exclude", "swipc-parser",
	"--",
	"@@split(CLIPPY_RULES, )",
	"${@}",
	]

[tasks.clippy-host-target]
workspace = false
description = "Run clippy on host components (relying on std)"
dependencies = ["install-rust-src", "refresh-crates"]
install_crate = { rustup_component_name = "clippy" }
command = "cargo"
args = ["clippy",
	"-p", "swipc-gen", "-p", "swipc-parser",
	"--",
	"@@split(CLIPPY_RULES, )",
	"${@}",
	]

[tasks.clippy]
workspace = false
dependencies = ["clippy-host-target", "clippy-sunrise-target"]

[tasks.swipc-gen]
workspace = false
description = "Get the output of running gen_ipc on an ipcdef file"
command = "cargo"
args = ["run", "--manifest-path", "swipc-gen/Cargo.toml", "--features=binaries", "--", "${@}"]

[tasks.default]
workspace = false
run_task = "qemu"
