[package]
name = "kfs-libuser"
version = "0.1.0"
authors = ["roblabla <unfiltered@roblab.la>", "orycterope <tvermeilh@gmail.com>"]

[dependencies]
linked_list_allocator = "0.6.2"
bitfield = "0.13"
bit_field = "0.9"
spin = "0.4"
kfs-libutils = { path = "../libutils" }
kfs-libkern = { path = "../libkern" }
failure = { version = "0.1", default-features = false, features = ["derive"] }
font-rs = { git = "https://github.com/orycterope/font-rs" }
hashmap_core = "0.1.9"

[dependencies.byteorder]
default-features = false
version = "1.2.7"

[dependencies.arrayvec]
default-features = false
version = "0.4.9"
